**This notebooks aims at keeping track of interesting concepts or topics throughout the course. It also serves as a test environment.**

In [1]:
import numpy as np
import pandas as pd

ModuleNotFoundError: No module named 'numpy'

*Array attributes and methods*

In [3]:
# np.random.seed concept 
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [7]:
# Array attributes and methods

arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [8]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([41, 48, 32, 20, 22, 22, 10, 21, 27, 28])

In [9]:
#Reshape

arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
# location of max,min

ranarr.max()
ranarr.min()
ranarr.argmax() # arg will return the index of the maximum value in the array
ranarr.argmin() # arg will return the index of the minimum value in the array

1

*indexing and selection*

In [15]:
arr= np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# Array manipulation and two way dependance

slice_of_arr = arr[0:6]
slice_of_arr
slice_of_arr[:] = 99
slice_of_arr
arr
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [25]:
# indexing on 2D array

arr_2nd = np.array([[1, 2, 3], [4, 5,20], [6,21,10]])
arr_2nd

array([[ 1,  2,  3],
       [ 4,  5, 20],
       [ 6, 21, 10]])

In [31]:
arr_2nd[1,1]
arr_2nd[1][1] 

# both equivalent

arr_2nd[2,2]
arr_2nd[:2,1:]

array([[ 2,  3],
       [ 5, 20]])

In [38]:
#conditional selection

arr = np.arange(1,11)
arr
arr > 4
bool_ar = arr > 4
arr[bool_ar] # = arr[arr>4]
#arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [42]:
# Numpy operations 

arr *2 
arr + arr
arr = arr -1 
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr.sum()
arr.mean()

4.5

In [51]:
arr_2nd = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])
arr_2nd.shape
arr_2nd.sum()

78

In [52]:
arr_2nd.shape
arr_2nd.sum(axis=0) # sum of the values in the columns
arr_2nd.sum(axis=1) # sum of the values in the rows

array([15, 18, 21, 24])

**Section 4. PANDA**

In [ ]:
# Difference between a series and an array is that a series will have a named index

In [11]:
import pandas as pd
import numpy as np

In [12]:
from numpy.random import randn
np.random.seed(101)

rand_mat = randn(5,4)

In [13]:
rand_mat

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [14]:
df = pd.DataFrame(data=rand_mat, index= 'A B C D E'.split(), columns='W X Y Z'.split())
df


W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [15]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [16]:
 df.iloc[2:4]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [18]:
df = pd.DataFrame({'col1':[1,2,3,5], 'col2':[444,555,666,444], 'col3':['abc','def','ghi','xyz']})
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     5   444  xyz

In [20]:
#unique values

len(df['col2'].unique())
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [21]:
def times_two(number):
    return number * 2

In [22]:
times_two(4)

8

In [25]:
df['new']=df['col1'].apply(times_two)
df

col1  col2 col3  new
0     1   444  abc    2
1     2   555  def    4
2     3   666  ghi    6
3     5   444  xyz   10

In [39]:
df.sort_values(by = 'col2', inplace = True)
df

col1  col2 col3
0     1   444  abc
3     5   444  xyz
1     2   555  def
2     3   666  ghi

In [45]:
pd.read_csv('C:\\Users\\Simon\\Documents_local\\GitHub2\\UdemyTimeSeries\\Udemy_TimeSeries_res\\02-Pandas\\example.csv')

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15